version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      local-backend:
        patterns:
          - candle-*
          - tokenizers
          - hf-hub

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
